
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDEnonassocUMINUSDIVIDE LPAREN MINUS NUMBER PLUS RPAREN TIMESexpression : expression PLUS termexpression : expression MINUS termexpression : MINUS expression %prec UMINUSexpression : termterm : term TIMES factorterm : term DIVIDE factorterm : factorfactor : NUMBERfactor : LPAREN expression RPAREN'
    
_lr_action_items = {'MINUS':([0,1,2,3,4,5,6,11,12,13,14,15,16,17,],[3,8,-4,3,-7,-8,3,-3,8,-1,-2,-5,-6,-9,]),'NUMBER':([0,3,6,7,8,9,10,],[5,5,5,5,5,5,5,]),'LPAREN':([0,3,6,7,8,9,10,],[6,6,6,6,6,6,6,]),'$end':([1,2,4,5,11,13,14,15,16,17,],[0,-4,-7,-8,-3,-1,-2,-5,-6,-9,]),'PLUS':([1,2,4,5,11,12,13,14,15,16,17,],[7,-4,-7,-8,-3,7,-1,-2,-5,-6,-9,]),'RPAREN':([2,4,5,11,12,13,14,15,16,17,],[-4,-7,-8,-3,17,-1,-2,-5,-6,-9,]),'TIMES':([2,4,5,13,14,15,16,17,],[9,-7,-8,9,9,-5,-6,-9,]),'DIVIDE':([2,4,5,13,14,15,16,17,],[10,-7,-8,10,10,-5,-6,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,6,],[1,11,12,]),'term':([0,3,6,7,8,],[2,2,2,13,14,]),'factor':([0,3,6,7,8,9,10,],[4,4,4,4,4,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','tpc6.py',43),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','tpc6.py',47),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','tpc6.py',52),
  ('expression -> term','expression',1,'p_expression_term','tpc6.py',56),
  ('term -> term TIMES factor','term',3,'p_term_times','tpc6.py',60),
  ('term -> term DIVIDE factor','term',3,'p_term_div','tpc6.py',64),
  ('term -> factor','term',1,'p_term_factor','tpc6.py',68),
  ('factor -> NUMBER','factor',1,'p_factor_num','tpc6.py',72),
  ('factor -> LPAREN expression RPAREN','factor',3,'p_factor_expr','tpc6.py',76),
]
