
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CODIGO LISTAR MOEDA MOEDAS SAIR SELECIONARcomando : LISTARcomando : MOEDA MOEDAScomando : SELECIONAR CODIGOcomando : SAIR'
    
_lr_action_items = {'LISTAR':([0,],[2,]),'MOEDA':([0,],[3,]),'SELECIONAR':([0,],[4,]),'SAIR':([0,],[5,]),'$end':([1,2,5,6,7,],[0,-1,-4,-2,-3,]),'MOEDAS':([3,],[6,]),'CODIGO':([4,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> LISTAR','comando',1,'p_comando_listar','tpc5.py',119),
  ('comando -> MOEDA MOEDAS','comando',2,'p_comando_moeda','tpc5.py',123),
  ('comando -> SELECIONAR CODIGO','comando',2,'p_comando_selecionar','tpc5.py',128),
  ('comando -> SAIR','comando',1,'p_comando_sair','tpc5.py',132),
]
